version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: ecommercebuilder
      POSTGRES_PASSWORD: ecomerce
      POSTGRES_DB: ecommercebuilder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
