services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:${DATABASE_PORT}"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
